# Generated by Django 5.0.6 on 2024-06-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notion',
            name='cover',
            field=models.ImageField(blank=True, upload_to='covers/<django.db.models.fields.CharField>/'),
        ),
    ]
