# Generated by Django 5.0.6 on 2024-05-29 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_alter_page_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
